name: Build

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
          gradle-version: current

      - name: mc-publish
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: xXNP32XJ
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 407488
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: build/libs/!(*-@(javadoc|sources)).jar
          version-type: release
          loaders: neoforge
          game-versions: 1.21
          java: 21
          name: ""
          changelog-file: changelog-1.21.*
