name: Build

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1000
          fetch-tags: true
      - name: Zip it up
        uses: thedoctor0/zip-release@0.7.5
        with:
           type: 'zip'
           filename: 'sfw_skeletons.zip'
           exclusions: '*.git* /*files/* .editorconfig'
      - name: mc-publish
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          files: |
                 sfw_skeletons.zip
          github-token: ${{ secrets.GITHUB_TOKEN }}
          modrinth-id: xXNP32XJ
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 1094620
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          version-type: release
          loaders: |
            neoforge
            fabric
            quilt
            forge
          version: 1.0.0
          game-versions: |
               [1.20.1, 1.21.1]
          name: ""
