name: Build

on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1000
          fetch-tags: true
      - name: Zip it up
        uses: thedoctor0/zip-release@0.7.5
        with:
           type: 'zip'
           filename: 'sfw_skeletons.zip'
           directory: 'files'
           exclusions: '*.git* /files/'
      - name: mc-publish
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          files: |
                 files/sfw_skeletons.zip
          modrinth-id: xXNP32XJ
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 407488
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          version-type: release
          version: 1.0.0
          loaders: neoforge
          game-versions: |
               (1.20.1, 1.21)
          java: 21
          name: ""
